### ISSUE TITLE
Regression: pdd started to fail on TODO comments that it ignored before

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#260]
The comments like `TODO:` were ignored before but after latest update, pdd tries to parse them and fails. It seems like a bug or a new feature that was implemented in non-backward compatible way.

See as example: https://github.com/php-coder/mystamps/commit/1a19a7dff7d373dc2b74d2c97511f8721521024d#commitcomment-31799391

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@php-coder it's a feature: https://github.com/yegor256/pdd/issues/106

**Comment by mbao01** [comment]
@php-coder thank you! This issue has been fixed in pdd [issue #156](https://github.com/yegor256/pdd/issues/156). This update will be coming soon to 0pdd once released on pdd. Pending that, please keep this issue open.

I will get back to you on the changelog.

**Comment by AntistasII** [comment]
@yegor256 @mbao01 has 0pdd been updated? This issue is still relevant?

**Comment by mbao01** [comment]
@AntistasII yes it has been updated)
